/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlineshop;

import java.text.SimpleDateFormat;
import javax.swing.*;
import java.sql.*;

public class Interface_Register extends javax.swing.JFrame {    
    Connection conn;
    
    public Interface_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        txt_title = new javax.swing.JTextField();
        lbl_fName = new javax.swing.JTextField();
        txt_fName = new javax.swing.JTextField();
        lbl_lName = new javax.swing.JTextField();
        txt_lName = new javax.swing.JTextField();
        lbl_email = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        lbl_birth = new javax.swing.JTextField();
        lbl_phone = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        lbl_address = new javax.swing.JTextField();
        lbl_pass = new javax.swing.JTextField();
        jpass_pass = new javax.swing.JPasswordField();
        lbl_conpass = new javax.swing.JTextField();
        jpass_conpass = new javax.swing.JPasswordField();
        bt_register = new javax.swing.JButton();
        bt_login = new javax.swing.JButton();
        dt_birth = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        txta_address = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(788, 981));

        jPanel2.setBackground(new java.awt.Color(188, 218, 221));

        txt_title.setEditable(false);
        txt_title.setBackground(new java.awt.Color(255, 255, 204));
        txt_title.setFont(new java.awt.Font("Mshtakan", 0, 36)); // NOI18N
        txt_title.setText(" R E G I S T E R");
        txt_title.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_titleActionPerformed(evt);
            }
        });

        lbl_fName.setEditable(false);
        lbl_fName.setBackground(new java.awt.Color(188, 218, 221));
        lbl_fName.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_fName.setForeground(new java.awt.Color(51, 51, 51));
        lbl_fName.setText("First Name");
        lbl_fName.setBorder(null);
        lbl_fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_fNameActionPerformed(evt);
            }
        });

        txt_fName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_lName.setEditable(false);
        lbl_lName.setBackground(new java.awt.Color(188, 218, 221));
        lbl_lName.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_lName.setForeground(new java.awt.Color(51, 51, 51));
        lbl_lName.setText("Last Name");
        lbl_lName.setBorder(null);
        lbl_lName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_lNameActionPerformed(evt);
            }
        });

        txt_lName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_email.setEditable(false);
        lbl_email.setBackground(new java.awt.Color(188, 218, 221));
        lbl_email.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(51, 51, 51));
        lbl_email.setText("Email");
        lbl_email.setBorder(null);
        lbl_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_emailActionPerformed(evt);
            }
        });

        txt_email.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_birth.setEditable(false);
        lbl_birth.setBackground(new java.awt.Color(188, 218, 221));
        lbl_birth.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_birth.setForeground(new java.awt.Color(51, 51, 51));
        lbl_birth.setText("Birth Date");
        lbl_birth.setBorder(null);
        lbl_birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_birthActionPerformed(evt);
            }
        });

        lbl_phone.setEditable(false);
        lbl_phone.setBackground(new java.awt.Color(188, 218, 221));
        lbl_phone.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_phone.setForeground(new java.awt.Color(51, 51, 51));
        lbl_phone.setText("Phone Number");
        lbl_phone.setBorder(null);
        lbl_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_phoneActionPerformed(evt);
            }
        });

        txt_phone.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_address.setEditable(false);
        lbl_address.setBackground(new java.awt.Color(188, 218, 221));
        lbl_address.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_address.setForeground(new java.awt.Color(51, 51, 51));
        lbl_address.setText("Address");
        lbl_address.setBorder(null);
        lbl_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_addressActionPerformed(evt);
            }
        });

        lbl_pass.setEditable(false);
        lbl_pass.setBackground(new java.awt.Color(188, 218, 221));
        lbl_pass.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_pass.setForeground(new java.awt.Color(51, 51, 51));
        lbl_pass.setText("Password");
        lbl_pass.setBorder(null);
        lbl_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_passActionPerformed(evt);
            }
        });

        jpass_pass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_conpass.setEditable(false);
        lbl_conpass.setBackground(new java.awt.Color(188, 218, 221));
        lbl_conpass.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_conpass.setForeground(new java.awt.Color(51, 51, 51));
        lbl_conpass.setText("Confirm Password");
        lbl_conpass.setBorder(null);
        lbl_conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_conpassActionPerformed(evt);
            }
        });

        jpass_conpass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        bt_register.setText("REGISTER");
        bt_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registerActionPerformed(evt);
            }
        });

        bt_login.setText("BACK TO LOGIN");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        txta_address.setBackground(new java.awt.Color(240, 240, 240));
        txta_address.setColumns(20);
        txta_address.setRows(5);
        jScrollPane3.setViewportView(txta_address);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txt_fName, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txt_lName, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(dt_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lbl_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jpass_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lbl_conpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jpass_conpass, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(bt_register))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(bt_login)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lbl_fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txt_fName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txt_lName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(dt_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbl_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jpass_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_conpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jpass_conpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bt_register)
                .addGap(18, 18, 18)
                .addComponent(bt_login)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_titleActionPerformed

    private void lbl_fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_fNameActionPerformed

    private void lbl_lNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_lNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_lNameActionPerformed

    private void lbl_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_emailActionPerformed

    private void lbl_birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_birthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_birthActionPerformed

    private void lbl_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_phoneActionPerformed

    private void lbl_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addressActionPerformed

    private void lbl_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_passActionPerformed

    private void lbl_conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_conpassActionPerformed

    private void bt_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_registerActionPerformed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_loginActionPerformed

    public boolean checkEmailTaken(String email){
        PreparedStatement ps;
        ResultSet rs;
        boolean checkEmail = false;
        String query = "SELECT * FROM COSTUMER WHERE EMAIL =?";
        
        try{
            conn = new ConnectionSQL().getConSQL();
            ps = conn.prepareStatement(query);
            ps.setString(1, email);
            rs = ps.executeQuery();
            
            if(rs.next()){
                checkEmail = true;
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        return checkEmail;
    }
    
    public void resetFill(){
        txt_fName.setText("");
        txt_lName.setText("");
        txt_email.setText("");
        dt_birth.setDate(null);
        txta_address.setText("");
        txt_phone.setText("");
        jpass_pass.setText("");
        jpass_conpass.setText("");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_register;
    private com.toedter.calendar.JDateChooser dt_birth;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPasswordField jpass_conpass;
    private javax.swing.JPasswordField jpass_pass;
    private javax.swing.JTextField lbl_address;
    private javax.swing.JTextField lbl_birth;
    private javax.swing.JTextField lbl_conpass;
    private javax.swing.JTextField lbl_email;
    private javax.swing.JTextField lbl_fName;
    private javax.swing.JTextField lbl_lName;
    private javax.swing.JTextField lbl_pass;
    private javax.swing.JTextField lbl_phone;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fName;
    private javax.swing.JTextField txt_lName;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_title;
    private javax.swing.JTextArea txta_address;
    // End of variables declaration//GEN-END:variables
}
