/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlineshop;

import java.awt.Component;
import java.awt.Toolkit;
import javax.swing.*;
import java.sql.*;
import java.awt.event.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import co.yogesh.Captcha;
import java.util.Locale;
        

/**
 *
 * @author cherriegracilaamanda
 */
public class Interface_Login extends javax.swing.JFrame {

    Connection conn;
    Object currentWindow = this;    
    
    String email, pass;
    int attempt = 3;
//    int second = 30;
//    Timer timer;
    
    Captcha cap = new Captcha();
    public Interface_Login() {
        initComponents();
        setIconImage();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        cap.setImageCaptcha(lbl_captcha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        lbl_captcha = new javax.swing.JLabel();
        txt_titlePass = new javax.swing.JTextField();
        txt_titleEmail = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jpass_pass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        bt_create = new javax.swing.JButton();
        bt_signIn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_titleCaptcha = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_aboutUs = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbl_answer = new javax.swing.JLabel();
        txt_answerCaptcha = new javax.swing.JTextField();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lbl_captcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 240, 90));

        txt_titlePass.setEditable(false);
        txt_titlePass.setFont(new java.awt.Font("Orator Std", 0, 16)); // NOI18N
        txt_titlePass.setForeground(new java.awt.Color(51, 51, 51));
        txt_titlePass.setText(" P A S S W O R D");
        txt_titlePass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_titlePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 180, 40));

        txt_titleEmail.setEditable(false);
        txt_titleEmail.setFont(new java.awt.Font("Orator Std", 0, 16)); // NOI18N
        txt_titleEmail.setForeground(new java.awt.Color(51, 51, 51));
        txt_titleEmail.setText(" E M A I L");
        txt_titleEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_titleEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 40));

        txt_email.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 230, 50));

        jpass_pass.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jpass_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/welcome-01 (2).png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 360, 100));

        bt_create.setText("CREATE NEW ACCOUNT");
        bt_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_createActionPerformed(evt);
            }
        });
        jPanel1.add(bt_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 640, -1, -1));

        bt_signIn.setText("SIGN IN");
        bt_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_signInActionPerformed(evt);
            }
        });
        jPanel1.add(bt_signIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 214, 198));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 290, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/divider-clipart-flower-10 (1).png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 280, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/divider-clipart-flower-10 (1).png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 280, 90));

        lbl_titleCaptcha.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
        lbl_titleCaptcha.setText("Please type the characters below to continue : ");
        jPanel1.add(lbl_titleCaptcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 214, 198));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 220, 20));

        lbl_aboutUs.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        lbl_aboutUs.setText("About Us");
        lbl_aboutUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_aboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_aboutUsMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_aboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, -1, 30));

        jPanel4.setBackground(new java.awt.Color(255, 214, 198));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 120, 20));

        jPanel5.setBackground(new java.awt.Color(255, 214, 198));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 190, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/kisspng-photography-desktop-wallpaper-fishs-tumblr-png-5ab1916890be41.1305519615215865365929 (1).png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel6.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 190, 140));

        lbl_answer.setText("Answer :");
        jPanel1.add(lbl_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));
        jPanel1.add(txt_answerCaptcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 180, 40));

        lbl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bg-05.png"))); // NOI18N
        lbl_bg.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanel1.add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_createActionPerformed
        Interface_Register ir = new Interface_Register();
        ir.setVisible(true);
        ir.pack();
        ir.setLocationRelativeTo(null);
        ir.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();            
    }//GEN-LAST:event_bt_createActionPerformed

    private void bt_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_signInActionPerformed
        String checkFill = checkFill();
        if(checkFill.equals("Valid") && isEmail()){
            set_data();
            boolean adm = isAdmin(email);
            
            // if admin
            if(adm){
                String login = new User().login_adm(email, pass);
                if(login.equals("Success") && cap.Validate(lbl_captcha, txt_answerCaptcha.getText())){
                    attempt = 3;
                    ManageProduct mp = new ManageProduct();
                    JOptionPane.showMessageDialog(null, login);
                    mp.setVisible(true);
                    mp.setSize(780, 650);
                    mp.setLocationRelativeTo(null);
                    mp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    mp.setResizable(false);
                    this.dispose();
                }
                // if wrong captcha
                else if(checkCaptcha(txt_answerCaptcha.getText())){
                    reset();
                    attempt--;
                    JOptionPane.showMessageDialog(null, "Wrong captcha");
                    actAttempt(attempt);
                }else{
                    reset();
                    attempt--;
                    JOptionPane.showMessageDialog(null, "Wrong email or password");
                    actAttempt(attempt);
                }
            }
            // if not an admin
            else{
                String login = new User().login_customer(email, pass);
                if(login.equals("Success") && cap.Validate(lbl_captcha, txt_answerCaptcha.getText())){
                    attempt = 3;
                    String fullName = new User().get_fullName(email, pass);
                    Olshop ol = new Olshop();
                    JOptionPane.showMessageDialog(null, login);
                    ol.login(fullName);
                    ol.setVisible(true);
                    ol.setSize(780, 650);
                    ol.setLocationRelativeTo(null);
                    ol.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    ol.setResizable(false);
                    this.dispose();
                }
                //if wrong captcha
                else if(checkCaptcha(txt_answerCaptcha.getText())){
                    attempt--;
                    reset();
                    JOptionPane.showMessageDialog(null, "Wrong captcha");
                    actAttempt(attempt);
                }else{
                    attempt--;
                    reset();
                   JOptionPane.showMessageDialog(null, "Wrong email or password");
                   actAttempt(attempt);
                }
            }
        }else if(!checkFill.equals("Valid")){
            JOptionPane.showMessageDialog(null, checkFill);
        }else if(isEmail() == false){
            JOptionPane.showMessageDialog(null, "Please enter your email correctly");
        }              
    }//GEN-LAST:event_bt_signInActionPerformed

    private void lbl_aboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aboutUsMouseClicked
	OurTeam ot = new OurTeam();
	ot.addWindowListener(new WindowAdapter() {
	public void windowClosing(WindowEvent ev) {
		((Component) currentWindow).setEnabled(true);
            }
	});
	((Component) currentWindow).setEnabled(false);
	ot.setLocationRelativeTo(null);
	ot.setResizable(false);
	ot.setVisible(true);
        ot.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);            
    }//GEN-LAST:event_lbl_aboutUsMouseClicked
    
    public void actAttempt(int attempt){
        if(attempt == 0){
            JOptionPane.showMessageDialog(null, "You've reached the maximum attempts for login, application shutting down");
            System.exit(0);
        }
    }
    
    public boolean checkCaptcha(String answer){
        boolean cond = true;
        if(cap.Validate(lbl_captcha, answer)){
            cond = false;
        }
        return cond;
    }
    
    public boolean isEmail(){
        Pattern pMail = Pattern.compile("^[a-zA-Z0-9._]+@[a-zA-Z0-9.]+\\.[a-zA-Z]{2,6}$");
        Matcher mMail = pMail.matcher(txt_email.getText());
        boolean cond = mMail.matches();
        // if true is email, if false is not an email
        return cond;
    }    
    
    public boolean isAdmin(String email){
        boolean cond = false;
        String[] emailAdm = {"sh1212@gmail.com", "chrrie0928@gmail.com", "dddblue6@gmail.com"};
        for(int i=0;i < emailAdm.length;i++){
            if(email.equals(emailAdm[i])){
                cond = true;
            }
        }
        return cond;
    }    
    
    
    public void set_data(){
        email = txt_email.getText().trim();
        pass = String.valueOf(jpass_pass.getPassword());
    }

    public void reset(){
        txt_email.setText("");
        jpass_pass.setText("");
        txt_answerCaptcha.setText("");
        cap.setImageCaptcha(lbl_captcha);
    }
    
    public String checkFill(){
        String result = "";
        if(txt_email.getText().equals("")){
            result = "Fill your email";
        }else if(String.valueOf(jpass_pass.getPassword()).equals("")){
            result = "Fill your password";
        }else if(txt_answerCaptcha.getText().equals("")){
            result = "Fill your captcha";
        }else{
            result = "Valid";
        }
        return result;
    }    
    
    private void setIconImage(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Newlogo-SE.png")));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Login().setVisible(true);
            }
        });
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_create;
    private javax.swing.JButton bt_signIn;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jpass_pass;
    private javax.swing.JLabel lbl_aboutUs;
    private javax.swing.JLabel lbl_answer;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_captcha;
    private javax.swing.JLabel lbl_titleCaptcha;
    private javax.swing.JTextField txt_answerCaptcha;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_titleEmail;
    private javax.swing.JTextField txt_titlePass;
    // End of variables declaration//GEN-END:variables
}
