/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlineshop;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Interface_Register extends javax.swing.JFrame {    
    Connection conn;
    String fName, lName, email, bdate, address, phoneNum, pass, conPass;
    public Interface_Register() {
        initComponents();
        txt_fName.setDocument(new OnlyLetter().getOnlyLetter());
        txt_lName.setDocument(new OnlyLetter().getOnlyLetter());
        txt_phone.setDocument(new OnlyDigit().getOnlyDigit());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setIconImage();
    }

    private void setIconImage(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("newLogo-SE.png")));
    }       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        txt_title = new javax.swing.JTextField();
        lbl_fName = new javax.swing.JTextField();
        txt_fName = new javax.swing.JTextField();
        lbl_lName = new javax.swing.JTextField();
        txt_lName = new javax.swing.JTextField();
        lbl_email = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        lbl_birth = new javax.swing.JTextField();
        lbl_phone = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        lbl_address = new javax.swing.JTextField();
        lbl_pass = new javax.swing.JTextField();
        jpass_pass = new javax.swing.JPasswordField();
        lbl_conpass = new javax.swing.JTextField();
        jpass_conpass = new javax.swing.JPasswordField();
        bt_register = new javax.swing.JButton();
        bt_login = new javax.swing.JButton();
        dt_birth = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        txta_address = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(788, 981));

        jPanel2.setBackground(new java.awt.Color(188, 218, 221));

        txt_title.setEditable(false);
        txt_title.setBackground(new java.awt.Color(255, 255, 204));
        txt_title.setFont(new java.awt.Font("Mshtakan", 0, 36)); // NOI18N
        txt_title.setText(" R E G I S T E R");
        txt_title.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_fName.setEditable(false);
        lbl_fName.setBackground(new java.awt.Color(188, 218, 221));
        lbl_fName.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_fName.setForeground(new java.awt.Color(51, 51, 51));
        lbl_fName.setText("First Name");
        lbl_fName.setBorder(null);

        txt_fName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_lName.setEditable(false);
        lbl_lName.setBackground(new java.awt.Color(188, 218, 221));
        lbl_lName.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_lName.setForeground(new java.awt.Color(51, 51, 51));
        lbl_lName.setText("Last Name");
        lbl_lName.setBorder(null);

        txt_lName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_email.setEditable(false);
        lbl_email.setBackground(new java.awt.Color(188, 218, 221));
        lbl_email.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(51, 51, 51));
        lbl_email.setText("Email");
        lbl_email.setBorder(null);

        txt_email.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_birth.setEditable(false);
        lbl_birth.setBackground(new java.awt.Color(188, 218, 221));
        lbl_birth.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_birth.setForeground(new java.awt.Color(51, 51, 51));
        lbl_birth.setText("Birth Date");
        lbl_birth.setBorder(null);

        lbl_phone.setEditable(false);
        lbl_phone.setBackground(new java.awt.Color(188, 218, 221));
        lbl_phone.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_phone.setForeground(new java.awt.Color(51, 51, 51));
        lbl_phone.setText("Phone Number");
        lbl_phone.setBorder(null);

        txt_phone.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_address.setEditable(false);
        lbl_address.setBackground(new java.awt.Color(188, 218, 221));
        lbl_address.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_address.setForeground(new java.awt.Color(51, 51, 51));
        lbl_address.setText("Address");
        lbl_address.setBorder(null);

        lbl_pass.setEditable(false);
        lbl_pass.setBackground(new java.awt.Color(188, 218, 221));
        lbl_pass.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_pass.setForeground(new java.awt.Color(51, 51, 51));
        lbl_pass.setText("Password");
        lbl_pass.setBorder(null);

        jpass_pass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_conpass.setEditable(false);
        lbl_conpass.setBackground(new java.awt.Color(188, 218, 221));
        lbl_conpass.setFont(new java.awt.Font("Sinhala MN", 2, 14)); // NOI18N
        lbl_conpass.setForeground(new java.awt.Color(51, 51, 51));
        lbl_conpass.setText("Confirm Password");
        lbl_conpass.setBorder(null);

        jpass_conpass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        bt_register.setText("REGISTER");
        bt_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registerActionPerformed(evt);
            }
        });

        bt_login.setText("BACK TO LOGIN");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        txta_address.setBackground(new java.awt.Color(240, 240, 240));
        txta_address.setColumns(20);
        txta_address.setRows(5);
        jScrollPane3.setViewportView(txta_address);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txt_fName, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txt_lName, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(dt_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lbl_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jpass_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lbl_conpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jpass_conpass, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(bt_register))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(bt_login)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lbl_fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txt_fName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txt_lName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(dt_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbl_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jpass_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_conpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jpass_conpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bt_register)
                .addGap(18, 18, 18)
                .addComponent(bt_login)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean isEmail(){
        Pattern pMail = Pattern.compile("^[a-zA-Z0-9._]+@[a-zA-Z0-9.]+\\.[a-zA-Z]{2,6}$");
        Matcher mMail = pMail.matcher(txt_email.getText());
        boolean cond = mMail.matches();
        // if true is email, if false is not an email
        return cond;
    }        

    public boolean checkPassword(){
        /*
        Password must:
        contains 8 characters and max 16 characters
        contains at least one digit
        contains at least one upper case alphabet
        contains at least one lower case alphabet
        it doesn't conatain any white space
        */
        String regex = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=\\S+$).{8,16}$";
        Pattern pPass = Pattern.compile(regex);
        Matcher mPass = pPass.matcher(pass);
        boolean cond = mPass.matches();
        // if true password condition is met
        return cond;
    }
    
    private void bt_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registerActionPerformed
    String checkFill = checkFill();
    if(checkFill.equals("Valid") && isEmail()){
        set_data();
        String checkPass = check_pass(pass, conPass);
        String checkEmail = checkEmailTaken(email);
        if(checkPassword()){
            if(checkPass.equals("Valid") && checkEmail.equals("Valid")){
                String save = new User().add_user(fName, lName, email, bdate, address, phoneNum, pass);
                JOptionPane.showMessageDialog(null, "New User Created");
                resetFill();   
            }else if(!checkPass.equals("Valid")){
            JOptionPane.showMessageDialog(null, checkPass);
            }else{
            JOptionPane.showMessageDialog(null, checkEmail);
            }            
        }else{
            JOptionPane.showMessageDialog(null, "The password requirements must be at least 8 characters and a maximum of 16 characters, there must be at least one digit, one lower case letter, one upper case letter, and there should be no spaces");
        }
    }else if(!checkFill.equals("Valid")){
        JOptionPane.showMessageDialog(null, checkFill);
    }else{
        JOptionPane.showMessageDialog(null, "Please enter your email correctly");
    }
    }//GEN-LAST:event_bt_registerActionPerformed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        Interface_Login il = new Interface_Login();
        il.setVisible(true);
        il.pack();
        il.setLocationRelativeTo(null);
        il.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_bt_loginActionPerformed

    public String check_pass(String pass, String conPass){
        String result = "";
        if(!conPass.equals(pass)){
            result = "Password not match";
        }else{
            result = "Valid";
        }
        return result;
    }
    
    public void set_data(){
        fName = txt_fName.getText();
        lName = txt_lName.getText();
        email = txt_email.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        bdate = dateFormat.format(dt_birth.getDate());
        address = txta_address.getText();
        phoneNum = txt_phone.getText();
        pass = String.valueOf(jpass_pass.getPassword());
        conPass = String.valueOf(jpass_conpass.getPassword());
    }
    
    public String checkFill(){
        String result = "";
        if(txt_fName.getText().equals("")){
            result = "Fill your first name";
        }else if(txt_lName.getText().equals("")){
            result = "Fill your last name";
        }else if(txt_email.getText().equals("")){
            result = "Fill your email";
        }else if(txt_phone.getText().equals("")){
            result = "Fill your phone number";
        }else if(String.valueOf(jpass_pass.getPassword()).equals("")){
            result = "Fill your password";
        }else if(String.valueOf(jpass_conpass.getPassword()).equals("")){
            result = "Fill your confirm password";
        }else if(dt_birth.getDate() == null){
            result = "Choose birth date";
        }else{
            result = "Valid";
        }
        return result;
    }
    
    public String checkEmailTaken(String email){
        String result = "";
        boolean cond = new User().check_email(email);
        if(cond){
            result = "Email: "+email+" has been taken";
        }else{
            result = "Valid";
        }
        return result;
    }
    
    public void resetFill(){
        txt_fName.setText("");
        txt_lName.setText("");
        txt_email.setText("");
        dt_birth.setDate(null);
        txta_address.setText("");
        txt_phone.setText("");
        jpass_pass.setText("");
        jpass_conpass.setText("");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_register;
    private com.toedter.calendar.JDateChooser dt_birth;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPasswordField jpass_conpass;
    private javax.swing.JPasswordField jpass_pass;
    private javax.swing.JTextField lbl_address;
    private javax.swing.JTextField lbl_birth;
    private javax.swing.JTextField lbl_conpass;
    private javax.swing.JTextField lbl_email;
    private javax.swing.JTextField lbl_fName;
    private javax.swing.JTextField lbl_lName;
    private javax.swing.JTextField lbl_pass;
    private javax.swing.JTextField lbl_phone;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fName;
    private javax.swing.JTextField txt_lName;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_title;
    private javax.swing.JTextArea txta_address;
    // End of variables declaration//GEN-END:variables
}
